name: Clear Hygraph

on:
  workflow_dispatch: {}

jobs:
  clear:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Run clear script
        run: npm run clear
        env:
          NEXT_PUBLIC_HYGRAPH_ENDPOINT: ${{ secrets.HYGRAPH_ENDPOINT }}
          NEXT_PUBLIC_HYGRAPH_TOKEN: ${{ secrets.HYGRAPH_TOKEN }}
